#%RAML 1.0
title: Lookup specs

uses:
  schema : schema/schema.raml

version: v1
protocols: [ HTTPS ]
baseUri: https://{host}:{port}/lookup-service/v1

documentation:
  - title: Description
    content: This document contains the API specification for the Emaratech. Lookup Service.

baseUriParameters:
  host:
    type: string
    description: The hostname or IP Address to target for the Lookup Service API.
    example: "lookup-service-qa"
    default: "lookup-service-qa"
  port:
      type: string
      description: The port at which the service is operating. It is optional, typically only for local deployments or non standard service instances.
      example: "8080"
      default: "8080"

/lookups:
    post:
      description: save the lookup object in the data store.
      body:
        application/json:
          type: schema.saveLookupRequest
          example: !include data/insert/saveLookupRequest.json
      responses:
        200:
          description: Returns the 200 response code if the lookup is stored successfully.
          body:
            application/json:
              type: schema.String
              example: !include data/insert/saveLookup200Response.json
        400:
            description: Returns the 400 response code if the request is incorrect.
            body:
              application/json:
                type: schema.Error
                example: !include data/insert/saveLookup-data-validation-400Response.json
                 example: !include data/insert/saveLookup-duplication-400Response.json
        500:
          description: Returns the 500 response code if there is any internal issue.
          body:
            application/json:
              type: schema.Error
              example: !include data/insert/saveLookup500Response.json
    delete:
      description: delete the lookup object in the data store.

      responses:
        200:
          description: Returns the 200 response code if the lookup is deleted successfully.
        400:
          description: Returns the 400 response code if the request is incorrect.
          body:
            application/json:
              type: schema.Error
              example: !include data/delete/deleteLookup400Response.json
        500:
          description: Returns the 500 response code if there is any internal issue.
          body:
            application/json:
              type: schema.Error
              example: !include data/delete/deleteLookup500Response.json
/lookups/{lookupType}:
  uriParameters:
      lookupType:
        type: string
        description: The lookup request identifier value.
        displayName: lookupType
        required: true
        example: Country
  get:
      description: Fetches the lookup data.
      responses:
          200:
            description: Returns the 200 response code
            body:
              application/json:
                type: schema.LookupResponse
                example: !include data/get/getLookupList200Response.json.json
          404:
            description: Returns 404 response code if the lookup corresponding to the lookup data is not present.
            body:
              application/json:
                type: schema.Error
                example: !include data/get/getLookup404Response.json
          500:
            description: Returns the 500 response code if there is any internal issue.
            body:
              application/json:
                type: schema.Error
                example: !include data/get/getLookup500Response.json
